### ISSUE TITLE
💻  Add Index Page

### ISSUE THREAD

**Issue by BrainonSilicon** [BrainonSilicon/mars-book-test#2]
About
---
* Project Name: Alternative Glossary 
* Link to Directory: [alternative-glossary](https://github.com/BrainonSilicon/mars-book-test/tree/main/alternative-glossary)

Background Information
---
Currrently it would be useful to implement a JupyterBook Index page into the site so that each of the glossary pages' entries can be compiled and found in a single place. 

When I tried to create an index file after reading [JupyterBook's documentation](https://jupyterbook.org/en/stable/content/content-blocks.html#content-indexes), the index page did not populate with terms, and it also over wrote the homepage as being the first viewed page. 

 What's Needed?
---
* Suggested solutions are needed (please feel free to make a PR and comment on this Issue) for creating an index page that compiles the terms used in the glossary sub pages.

Who Can Help?
---
@sgibson91 or @choldgraf who may have insight into JupyterBook.

**Comment by sgibson91** [comment]
The book _does_ generate an index. It is available at: https://brainonsilicon.github.io/mars-book-test/genindex.html

I think the question for this issue is "How do we make the Index available in the left hand side menu?" as I suspect that is where you were expecting to find it @BrainonSilicon.

**Comment by sgibson91** [comment]
I think this is the documentation we need to follow: https://jupyterbook.org/en/stable/content/content-blocks.html#add-the-general-index-to-your-table-of-contents

I don't currently see a `genindex.md` file in the `alternative-glossary` directory and the `_toc.yml` file will also need editing to add the `genindex.md` file as an entry. Leave `root: homepage` in the TOC as is to not overwrite the homepage.

**Comment by sgibson91** [comment]
I also did a search for the `{index}` directive in the repo and got zero hits, which implies that you haven't added any terms to the index, and that's why there's nothing being populated. https://jupyterbook.org/en/stable/content/content-blocks.html#the-index-directive

**Comment by BrainonSilicon** [comment]
Issue has been fixed:
---

The only thing that is needed in your genindex.md file is an H1 title 
* e.g. `# My Index`

To fix the index as first page issue I needed to name the index file as `genindex.md`
